name = "just"
version = "1.1.0"

description = "A JavaScript lexer and syntax highlighter for Gleam!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "GearsDatapacks", repo = "just" }
links = []

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_community_ansi = ">= 1.4.3 and < 2.0.0"
houdini = ">= 1.1.0 and < 2.0.0"
splitter = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"
birdie = ">= 1.2.6 and < 2.0.0"

[javascript.deno]
allow_read = ["gleam.toml", "test", "build", "birdie_snapshots"]
allow_write = ["birdie_snapshots"]
